-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT T.ITEM_ID
                FROM ITEM_INFO I, ITEM_TREE T
                WHERE RARITY = 'RARE' AND PARENT_ITEM_ID = I.ITEM_ID)
ORDER BY ITEM_ID DESC;